const:
  default-page-size: 20

file:
  directory: D:\KWJ\feed

mybatis:
  mapper-locations: mappers/**/*.xml

spring:
  application:
    name: GreenGramVer2
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://localhost/modir
    username: root
    password: dc09150915!@
  servlet:
    multipart:
      max-file-size: 15MB

springdoc:
  swagger-ui:
    default-model-expand-depth: 10
    display-request-duration: true
    groups-order: asc
    operations-sorter: method
    path: /swagger
    tags-sorter: alpha
  cache:
    disabled: true

jwt:
  secret: 7uHx5WOJQDKvEfEU53Lab5zKTvDHAW4fx4GDqIoaPufXe4aS6i/4+RCWk6UV1bI0bYwq2kUOavw+hUIDRI31+w==

