spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://yamabiko.proxy.rlwy.net:21274/railway
    username: railway
    password: i4PFvotaSxP0ENd0wsABOC6cDe4MYLvN

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
